### ISSUE TITLE
Embed-Layout kaputt

### ISSUE THREAD

**Issue by netAction** [nutztherookie/magda#10]
Geht nicht.

Beispiel-Eingabe: **https://www.youtube.com/watch?v=LF39mdJkOvQ**

**Comment by nutztherookie** [comment]
@netAction  hast du n beispiel wo du meinst dass das mit ner URL direkt geht? ich seh das im vanilla wagtail nciht, dass der da clever parst

**Comment by nutztherookie** [comment]
lol geil. gefunden. fieser bug. fixed.
