### ISSUE TITLE
Open Graph

### ISSUE THREAD

**Issue by netAction** [nutztherookie/magda#2]
Daten für jede Seite festlegen

**Comment by netAction** [comment]
Ins HTML jeder Seite sollten folgende Daten, wobei Title, Description und Image auf jeder Seite einzeln eingestellt werden können. Url muss die Adresse der jeweiligen Seite sein.

    <meta property="og:title" content="Graphic Recording | Sauschnell"/>
    <meta property="og:url" content="http://sauschnell.com/graphic-recording/"/>
    <meta property="og:site_name" content="Sauschnell"/>
    <meta property="og:description" content="How much does culture influence creative thinking?" />
    <meta property="og:image" content="http://sauschnell.com/media/images/graphic-recording-igmetall.max-800x800.png"/>

Das Bild sollte mindestens 1200x630 groß sein.

Zum Testen kann der Sharing Debugger vewendet werden:
https://developers.facebook.com/tools/debug/sharing/?q=sauschnell.com

**Comment by nutztherookie** [comment]
@netAction der will ne fb:app_id  sowas hamwer aber nicht. alternativ koennte man wohl machen
`<meta property="fb:admins" content="USER_ID"/>` 
gib ma senf :hotdog:

**Comment by netAction** [comment]
Keine App ID. So wie ich das oben geschrieben habe.

Doku: https://developers.facebook.com/docs/sharing/webmasters

**Comment by nutztherookie** [comment]
oben geschrieben? na jedenfalls, das von obn is drin aber er meckert eben ueber fehlende app_id

**Comment by netAction** [comment]
Hm. Ich finde weder, was jetzt nicht geht, noch verstehe ich, warum die App ID gebraucht werden sollte. Du kannst ja das Feld global abfragen, und @Orble soll sich kümmern.

**Comment by nutztherookie** [comment]
scheint schon zu gehen. lediglich:
![image](https://cloud.githubusercontent.com/assets/320080/19107977/01f1297c-8aef-11e6-9dc8-2b2a8f5ac9f3.png)

**Comment by netAction** [comment]
Das  habe ich auch gesehen. Mehr Probleme aber nicht.

Ich dachte auch, dass Open Graph universeller verwendet wird, nicht nur von Facebook. Dann ergibt das mit der App ID überhaupt keinen Sinn.

https://wiki.diasporafoundation.org/FAQ_for_web_developers

**Comment by nutztherookie** [comment]
top. -> Close.
